var awsSubDomain = ".cloud"; // You can remove the subdomain component with ""

var awsRegions = [
    CNAME("aws-ap-northeast-2"+ awsSubDomain,"ap-northeast-2.amazonaws.com.", one_day),
    CNAME("aws-ap-northeast-3"+ awsSubDomain,"ap-northeast-3.amazonaws.com.", one_day),
    CNAME("aws-ap-northeast"+ awsSubDomain,"ap-northeast-1.amazonaws.com.", one_day),
    CNAME("aws-osaka"+ awsSubDomain,"ap-northeast-3.amazonaws.com.", one_day),
    CNAME("aws-ap-south"+ awsSubDomain,"ap-south-1.amazonaws.com.", one_day),
    CNAME("aws-ap-southeast-2"+ awsSubDomain,"ap-southeast-2.amazonaws.com.", one_day),
    CNAME("aws-ap-southeast"+ awsSubDomain,"ap-southeast-1.amazonaws.com.", one_day),
    CNAME("aws-beijing"+ awsSubDomain,"cn-north-1.amazonaws.com.cn.", one_day),
    CNAME("aws-ca"+ awsSubDomain,"ca-central-1.amazonaws.com.", one_day),
    CNAME("aws-california"+ awsSubDomain,"us-west-1.amazonaws.com.", one_day),
    CNAME("aws-cn-north"+ awsSubDomain,"cn-north-1.amazonaws.com.cn.", one_day),
    CNAME("aws-china"+ awsSubDomain,"cn-north-1.amazonaws.com.cn.", one_day),
    CNAME("aws-cn-northwest"+ awsSubDomain,"cn-northwest-1.amazonaws.com.cn.", one_day),
    CNAME("aws-eu-central"+ awsSubDomain,"eu-central-1.amazonaws.com.", one_day),
    CNAME("aws-eu-west-2"+ awsSubDomain,"eu-west-2.amazonaws.com.", one_day),
    CNAME("aws-eu-west-3"+ awsSubDomain,"eu-west-3.amazonaws.com.", one_day),
    CNAME("aws-eu-west"+ awsSubDomain,"eu-west-1.amazonaws.com.", one_day),
    CNAME("aws-ireland"+ awsSubDomain,"eu-west-1.amazonaws.com.", one_day),
    CNAME("aws-london"+ awsSubDomain,"eu-west-2.amazonaws.com.", one_day),
    CNAME("aws-mtl"+ awsSubDomain,"ca-central-1.amazonaws.com.", one_day),
    CNAME("aws-mumbai"+ awsSubDomain,"ap-south-1.amazonaws.com.", one_day),
    CNAME("aws-ningxia"+ awsSubDomain,"cn-northwest-1.amazonaws.com.cn.", one_day),
    CNAME("aws-ohio"+ awsSubDomain,"us-east-2.amazonaws.com.", one_day),
    CNAME("aws-paris"+ awsSubDomain,"eu-west-3.amazonaws.com.", one_day),
    CNAME("aws-sa-east"+ awsSubDomain,"sa-east-1.amazonaws.com.", one_day),
    CNAME("aws-saopaulo"+ awsSubDomain,"sa-east-1.amazonaws.com.", one_day),
    CNAME("aws-seoul"+ awsSubDomain,"ap-northeast-2.amazonaws.com.", one_day),
    CNAME("aws-singapore"+ awsSubDomain,"ap-southeast-1.amazonaws.com.", one_day),
    CNAME("aws-sydney"+ awsSubDomain,"ap-southeast-2.amazonaws.com.", one_day),
    CNAME("aws-tokyo"+ awsSubDomain,"ap-northeast-1.amazonaws.com.", one_day),
    CNAME("aws-us-east-2"+ awsSubDomain,"us-east-2.amazonaws.com.", one_day),
    CNAME("aws-us-east"+ awsSubDomain,"us-east-1.amazonaws.com.", one_day),
    CNAME("aws-us-west-2"+ awsSubDomain,"us-west-2.amazonaws.com.", one_day),
    CNAME("aws-oregon"+ awsSubDomain,"us-west-2.amazonaws.com.", one_day),
    CNAME("aws-us-west"+ awsSubDomain,"us-west-1.amazonaws.com.", one_day),
    CNAME("aws-us"+ awsSubDomain,"us-east-1.amazonaws.com.", one_day),
    CNAME("aws-virginia"+ awsSubDomain,"us-east-1.amazonaws.com.", one_day),
    CNAME("aws"+ awsSubDomain,"ca-central-1.amazonaws.com.", one_day)
]
